
#- plateform: rest
#  resource: "http://192.168.1.5:7125/printer/emergency_stop"


- platform: rest
  name: vz52 Emergency Stop
  resource: "http://192.168.1.5:7125/printer/emergency_stop"
  body_on: '{"action": "on"}'
  body_off: '{"action": "off"}'
  headers:
    Content-Type: 'application/json'
  is_on_template: >-
    {{ 'result' in value_json and (value_json.result.values() | list | first == "on") }}
    