- id: '1610148573862'
  alias: New Automation
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  - platform: state
    entity_id: binary_sensor.updater
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.ha_update_available
  - service: input_boolean.turn_off
    data: {}
    entity_id: input_boolean.ha_update_available
  mode: single
