homeassistant:
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customize/
  unit_system: imperial
  time_zone: America/New_York
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - !secret internal_ip
      - !secret external_ip

zone:
  - name: Home
    latitude: !secret lat
    longitude: !secret long
    radius: 400


binary_sensor manual: !include_dir_list binary_sensors
group: !include_dir_merge_named group/
automation: !include_dir_list automations
script: !include_dir_merge_named script/
input_boolean: !include_dir_merge_named input_boolean/
scene: !include scenes.yaml
sensor: !include_dir_list sensors
frontend: !include frontend.yaml
recorder: !include recorder.yaml
notify: !include_dir_list notify
switch: !include_dir_merge_named switches
utility_meter: !include_dir_merge_named utility_meters


default_config:
calendar:
ffmpeg:
map:
config:
wake_on_lan:
history:
http:
#  ip_ban_enabled: false
#  login_attempts_threshold: 5
websocket_api:

camera:
  - platform: local_file
    file_path: /custom_components/mail_and_packages/mail_none.gif
    name: mail_usps

weather:
  - platform: pirateweather
    api_key: !secret privateweather
    # Additional optional values:
    latitude: !secret lat
    longitude: !secret long
    mode: "hourly"
    name: Pirate Weather
