homeassistant:
  packages: !include_dir_named integrations
  customize: !include_dir_merge_named customize/
  unit_system: imperial
  country: US
  time_zone: America/New_York
  external_url: !secret external_url
  internal_url: !secret internal_url
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
      - !secret internal_ip
      - !secret external_ip

binary_sensor manual: !include_dir_list binary_sensors
group: !include_dir_merge_named group/
automation: !include_dir_list automations
script: !include_dir_merge_named script/
input_boolean: !include_dir_merge_named input_boolean/
input_button: !include_dir_merge_named input_buttons/
template: !include_dir_list templates
sensor: !include_dir_list sensors
frontend: !include frontend.yaml
recorder: !include recorder.yaml
notify: !include_dir_list notify
switch: !include_dir_merge_named switches
utility_meter: !include_dir_merge_named utility_meters
counter: !include_dir_merge_named counters
