
alias: "Arm Home Night Actitvation"

description: ''
trigger:
- platform: time
  at: '23:00:00'

condition:
- condition: state
  entity_id: input_boolean.alarm_away
  state: 'off'
- condition: state
  entity_id: input_boolean.alarm_home
  state: 'off'

action:
- service: input_boolean.turn_on
  entity_id: input_boolean.alarm_night

mode: single
