
alias: "home security activated notification"
trigger:
  platform: state
  entity_id: input_boolean.alarm_triggered
  from: 'on'
  to: 'off'
  variables:
    action_on: "{{ 'ON_' ~ entity_id }}"
    action_off: "{{ 'OFF_' ~ entity_id }}"

action:
  - service: notify.mobile_app_ed_s_cell_phone
    data:
      message: "Disarm system?"
      data:
        actions:
          - action: "{{ action_on }}"
            title: 'No'
          - action: "{{ action_off }}"
            title: 'Yes'

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_on }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_off }}"

  - choose:
      - conditions: "{{ wait.trigger.event.data.action == action_on }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.disarmed
      - conditions: "{{ wait.trigger.event.data.action == action_off }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.disarmed