
alias: "Notify apps when home security activated"
trigger:
  platform: state
  entity_id: input_boolean.alarm_triggered
  to: "on"
action:
- service: script.notify_engine
  data:
    who: 'ed'
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Disarm system? Tap yes."
    title:  "Home security system has been activated "
    data:
      actions:
        - action: URI
          title:  "Yes"
          uri: '/lovelace/home'
        - action: "close_nope"
          title: "Nope"