
alias: "Notify apps when home security activated"
trigger:
- event_data:
    action: disarm_yes
  event_type: fcm_android_notifications.clicked
  platform: event
condition: []
action:
- data:
    entity_id: alarm_control_panel.alarmo
  service: alarm_control_panel.alarm_disarm