
alias: Sync group. nest_smake_alarm with input_boolean.smaoke_alarm 
trigger:
  platform: state
  entity_id: group.smoke_alarms
  from: 'off'
  to: 'on'

action:
  service: input_boolean.turn_on 
  entity_id: input_boolean.smoke_alarms