
alias: Disarm Night Someone is Up

description: 'Disarms security system someone is up'

trigger:
- platform: state
  entity_id: binary_sensor.living_room_protect_3
  to: "on"

condition:
- condition: state
  entity_id: input_boolean.alarm_night
  state: 'on'

action:
- service: input_boolean.turn_on
  entity_id: input_boolean.disarmed
- service: light.turn_on
  entity_id: light.kitchen_light

mode: single