alias: "Notify apps when the garage door opens"
trigger:
  platform: state
  entity_id: cover.ed_s 
  to: open 
  for: 00:02:00
action:
  service: notify.android
  data:
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Close Door? Tap yes."
    title:  "Ed's garage door has been left open"
    data:
      actions:
        - action: "close_yes"
          title:  "Yes"
        - action: "close_nope"
          title: "Nope"