
alias: "Notify apps when the garage door left open"
trigger:
    platform: state
    entity_id: cover.ed_s 
    to: open 
    for: 00:30:00
action:
  - service: notify.mobile_app_sm_n960u
    data:
      message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Close Door? Tap yes."
      title:  "Ed's garage door has been left open"
      data:
        actions:
          - action: URI
            title:  "Yes"
            uri: '/lovelace/home'
          - action: "close_nope"
            title: "Nope"

