
alias: "Notify apps when the garage door opens"
trigger:
  platform: state
  entity_id: cover.ed_s 
  to: open 
  for: 00:05:00
action:
  service: notify.mobile_app_sm_n960u
  data:
    message: "{{ as_timestamp(now()) | timestamp_custom('%I:%M%p', true) }} - Close Door? Tap yes."
    title: "Ed's Garage Door is Open"
    target: "notify.mobile_app_sm_n960u"
    data:
      actions:
        - action: "URI"
          title: "Yes"
          uri: http://74.41.160.118:8123/lovelace/garage
        - action: "close_covernope"
          title: "Nope"

