blueprint:
  name: Automated Daily Snapshot
  description: Create a full snapshot backup at a given time every day.
  domain: automation
  input:
    trigger_time:
      name: Snapshot creation time
      description: The snapshot will be created at this time, every day
      selector:
        time: {}
    send_notification:
      name: Send notification
      description: Sends a notification to a device if enabled
      selector:
        boolean: {}
      default: false
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive
        notifications
      selector:
        device:
          integration: mobile_app
      default: ''
  source_url: https://community.home-assistant.io/t/create-automated-backups-every-day/254039
mode: single
max_exceeded: silent
variables:
  backup_filename: Automated backup {{ now().strftime('%F') }}
  send_notification: !input 'send_notification'
  notify_device: !input 'notify_device'
  notification_title: Automated Daily Backup
  notification_message: Home Assistant full backup created. {{ now().strftime('%F')
    }}
trigger:
- platform: time
  at: !input 'trigger_time'
action:
- service: hassio.snapshot_full
  data:
    name: '{{ backup_filename }}'
- choose:
  - conditions: '{{ send_notification }}'
    sequence:
    - device_id: !input 'notify_device'
      domain: mobile_app
      type: notify
      title: '{{ notification_title }}'
      message: '{{ notification_message }}'
