blueprint:
  name: Turn off charging after device is charged
  description: Turn off the smart plug/relay after the device is charged to a given
    percent.
  domain: automation
  input:
    switch:
      name: Smart plug
      description: Smart plug/relay to turn off
      selector:
        entity:
          domain: switch
    phone_battery:
      name: Phone Battery
      description: Battery level sensor
      selector:
        entity:
          domain: sensor
          device_class: battery
    charged_percent:
      name: Charge percent
      description: Charge device to this percent
      selector:
        number:
          min: 0.0
          max: 100.0
          unit_of_measurement: '%'
          mode: box
          step: 1.0
      default: 100
  source_url: https://community.home-assistant.io/t/turn-off-phone-charging-after-the-phone-is-charged/253939
variables:
  phone_battery: !input 'phone_battery'
  charged_percent: !input 'charged_percent'
trigger:
- platform: state
  entity_id: !input 'phone_battery'
condition:
  condition: template
  value_template: '{{ (states(phone_battery)|int) >= (charged_percent|int) }}'
action:
- service: switch.turn_off
  entity_id: !input 'switch'
