
alias: Power restored UPS battery charging

trigger:
- platform: state
  entity_id: sensor.ups_status
  from: On Battery Battery Discharging
  to: Online Battery Charging

action:
- service: script.notify_engine
  data:
    who: 'ed'
    message: "Power restored, UPS battery charging"
- service: input_boolean.turn_off
  data: {}
  entity_id: input_boolean.ups_on_batteries
