
alias: Power Failure

trigger:
- platform: state
  entity_id: sensor.ups_status
  to: On Battery Battery Discharging

action:
- service: script.notify_engine
  data:
    who: 'ed'
    message: "Power Failure! UPS running!"

- service: input_boolean.turn_on
  data: {}
  entity_id: input_boolean.ups_on_batteries