
alias: UPS battery charged

trigger:
- platform: state
  entity_id: sensor.ups_battery_charge
  to: '100'

action:
- service: input_boolean.turn_off
  data: {}
  entity_id: input_boolean.ups_battery_charging