
alias: Home Assistant Update Notification

trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sensor.latest_version

condition:
  - condition: template
    value_template: >
      {{
      states("sensor.latest_version") != states("sensor.current_version")
      and states("sensor.latest_version") != "unknown"
      and states("sensor.latest_version") != states("input_text.version_latest_notified")
      }}
action:
# Set input text to latest HA value
  - service: input_text.set_value
    data:
      entity_id: input_text.version_latest_notified
      value: '{{ states("sensor.latest_version") }}'
  - service: input_boolean.turn_off
    entity_id: input_boolean.ha_update_available