
alias: HACS Updates Noticication off

trigger:
  - platform: state
    entity_id: sensor.hacs
    to: '0'

action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.hacs_updates_available