binary_sensor:
  - name: Livingroom Window 2
    device_class: opening
    state: >
      {{ is_state("binary_sensor.livingroom_window_2_iaszone", "on") }}
    icon: >
      {% if is_state("binary_sensor.livingroom_window_2_iaszone", "on") %}
        mdi:window-open
      {% else %}
        mdi:window-closed  
      {% endif %}