binary_sensor:
  - name: Master Bath Window 
    device_class: opening
    state: >
      {{ is_state("binary_sensor.master_bath_window_iaszone", "on") }}
    icon: >
      {% if is_state("binary_sensor.master_bath_window_iaszone", "on") %}
        mdi:window-open
      {% else %}
        mdi:window-closed  
      {% endif %}