binary_sensor:
  - name: Master Bedroom Window 2
    device_class: opening
    state: >
      {{ is_state("binary_sensor.ewelink_ds01_3e629623_ias_zone", "on") }}
    icon: >
      {% if is_state("binary_sensor.ewelink_ds01_3e629623_ias_zone", "on") %}
        mdi:window-open
      {% else %}
        mdi:window-closed  
      {% endif %}