blueprint:
  name: Move on holiday
  description: Loop through all calculated dates, move the collection to the next
    day  if public holiday is scheduled on the calculated collection date.  This does
    not move the collection if the holiday was in the week before the collection.
    For that, use the holiday_in_week blueprint.
  domain: automation
  source_url: https://github.com/bruxy70/Garbage-Collection/blob/development/blueprints/move_on_holiday.yaml
  input:
    garbage_collection_entity:
      name: Garbage Collection Entity
      description: Triggered by the event for this entity.
      selector:
        entity:
          integration: garbage_collection
    holiday_entity:
      name: Holidays
      description: Entity containing the holidays - an instance of Holidays custom
        integration (available through HACS)
      selector:
        entity:
          integration: holidays
mode: parallel
trigger:
- platform: event
  event_type: garbage_collection_loaded
  event_data:
    entity_id: !input 'garbage_collection_entity'
action:
- variables:
    holiday_entity: !input 'holiday_entity'
- repeat:
    count: '{{ trigger.event.data.collection_dates | count }}'
    sequence:
    - condition: template
      value_template: '{{ trigger.event.data.collection_dates[repeat.index-1] in state_attr(holiday_entity,''holidays'')
        }}'
    - service: garbage_collection.offset_date
      data:
        entity_id: '{{ trigger.event.data.entity_id }}'
        date: '{{ trigger.event.data.collection_dates[repeat.index-1] }}'
        offset: "{%- set collection_date = as_datetime(trigger.event.data.collection_dates[repeat.index-1])\
          \ %} {%- set ns = namespace(offset=1, found=false) %} {%- for _ in range(7)\
          \ if not ns.found %}\n  {%- set d = ( collection_date + timedelta( days=ns.offset)\
          \ ) | as_timestamp | timestamp_custom(\"%Y-%m-%d\") %}\n  {%- if d in state_attr(holiday_entity,'holidays')\
          \ %}\n    {%- set ns.offset = ns.offset + 1 %}\n  {% else %}\n    {%- set\
          \ ns.found = true %}\n  {%- endif %}\n{% endfor %} {{ ns.offset }}"
- service: garbage_collection.update_state
  data:
    entity_id: '{{ trigger.event.data.entity_id }}'
