
alias: Sync synology update off
trigger:
  platform: state
  entity_id: update.ewvisualarts_dsm_update
  from: 'on'
  to: 'off'

action:
  service: input_boolean.turn_off  
  entity_id: input_boolean.synology_update_available