
alias: "Set up notification for open garage door"
trigger:
  platform: state
  entity_id: cover.ed_s
  to: open 
  for: 00:30:00
  variables:
    action_open: "{{ 'OPEN_' ~ entity_id }}"
    action_close: "{{ 'CLOSE_' ~ entity_id }}"
action:
  - service: notify.mobile_app_ed_s_cell_phone
    data:
      message: "Ed's garage door is left open. Do you want to close it?"
      data:
        actions:
          - action: "{{ action_open }}"
            title: Open
          - action: "{{ action_close }}"
            title: Close

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_open }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_close }}"

  - choose:
      - conditions: "{{ wait.trigger.event.data.action == action_open }}"
        sequence:
          - service: cover.open_cover
            target:
              entity_id: cover.ed_s
      - conditions: "{{ wait.trigger.event.data.action == action_close }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: cover.ed_s
