
alias: Bed time old man 
trigger:
  platform: time
  at: '22:45:00'

condition:
- condition: state
  entity_id: switch.office_light_relay
  state: 'on'

action:
- service: script.turn_on
  target:
    entity_id: script.timetoquit
