
alias: Bed time old man 
trigger:
  platform: time
  at: '23:00:00'

condition:
- condition: state
  entity_id: switch.in_wall_toggle_switch_current_value_3 
  state: 'on'

action:
- service: script.timetoquit
