  alias: Perform Auto Backup
  trigger:
    platform: time_pattern # Perform backup every 3 hours.
    hours: "/3"
  action:
    service: auto_backup.backup_partial # Only perform a partial backup to save storage.
    data:
      name: "Ma: {{ now().strftime('%a, %-I:%M %p (%d/%m/%Y)') }}"
      addons:
        - core_mariadb # It doesn't matter if you use the addon slug or name. Name is easier.
      keep_days: 2