
#####
# Triggers when there is new warning or error
# https://community.home-assistant.io/t/counter-warning-error-issue/85490/11
#####

alias: Count Home Assistant errors

trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      level: ERROR
    id: error
  - platform: event
    event_type: system_log_event
    event_data:
      level: WARNING
    id: warning

action:
  - choose:
    - conditions:
      - condition: trigger
        id: warning
      sequence:
        - service: counter.increment
          entity_id: counter.homeassistant_warnings
    - conditions:
      - condition: trigger
        id: error
      sequence:
        - service: counter.increment
          entity_id: counter.homeassistant_errors

mode: queued


