
alias: HACS Updates
mode: single

trigger:
  - platform: state
    entity_id: sensor.hacs

condition:
  - condition: numeric_state
    entity_id: sensor.hacs
    above: 0

action:
- service: script.notify_engine
  data:
    who: 'ed'
    title: 'HACS Update'
    value1: 'HACS has {{ states.sensor.hacs.state }} updates available:'
    value2: >
          {% for repo in states.sensor.hacs.attributes.repositories %}
          {{ repo.display_name }} {{ repo["installed_version"] }} -> {{repo["available_version"] }}

          {% endfor %}
    tag_id: 'update_hacs'
    sticky: 'false'
    group: ha_status
    color: '#ff8c0'
    clickAction: '/hacs/entry'