
alias: "Count Home Assistant Warnings"
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: WARNING
action:
  service: counter.increment
  target:
    entity_id: counter.homeassistant_warnings

