alias: Count Home Assistant Errors
trigger:
  platform: event
  event_type: system_log_event
  event_data:
    level: ERROR
action:
  service: counter.increment
  entity_id: counter.homeassistant_errors