alias: Sync input_boolean.colleen_is_home with device_tracker
trigger:
  platform: state
  entity_id: device_tracker.sm_n950u
action:
  service_template: >
    {% if is_state('device_tracker.sm_n950u', 'home') %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.colleen_is_home