
alias: Sync input_boolean.ed_is_home with device_tracker
trigger:
  platform: state
  entity_id: device_tracker.life360_colleen_williams
  to: away

action:
  service:
      input_boolean.turn_off 

  entity_id: input_boolean.colleen_is_home