alias: Sync input_boolean.ed_is_home with device_tracker
trigger:
  platform: state
  entity_id: device_tracker.life360_ed_williams

action:
  service_template: >
    {% if is_state('device_tracker.life360_ed_williams', 'home') %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.ed_is_home