
alias: Home Assistant Update Available
trigger:
  platform: state
  entity_id: binary_sensor.updater

action:
  service_template: >
    {% if is_state('binary_sensor.updater', 'on') %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.ha_update_available