
alias: HACS Updates Noticication
mode: single

trigger:
  - platform: state
    entity_id: sensor.hacs

condition:
  - condition: numeric_state
    entity_id: sensor.hacs
    above: 0

action:
- service: script.notify_engine
  data:
    who: 'ed'
    title: '*HACS Update*'
    value1: 'HACS Update(s) at {{ states("sensor.time") }}'
    value2: '{{state_attr("sensor.hacs","repositories")}}'
    value3: 'There is {{ states.sensor.hacs.state }} update.'
    tag_id: 'update_hacs'
    sticky: 'true'
    group: ha_status
    color: '#ff8c0'
    clickAction: '/hacs/entry'