
alias: 'Ink Alert'

trigger:
  platform: numeric_state
  entity_id:
    - sensor.hp_officejet_pro_9015_ink_black
    - sensor.hp_officejet_pro_9015_ink_cyan
    - sensor.hp_officejet_pro_9015_ink_magenta
    - sensor.hp_officejet_pro_9015_ink_yellow
  below: 05

action:
  service: persistent_notification.create
  data:
    message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }}%"
    title: 'Ink level low'
    notification_id: xyz