
alias: 'Ink Alert'

trigger:
  platform: numeric_state
  entity_id:
    - sensor.hp_officejet_pro_9010_series_black_cartridge
    - sensor.hp_officejet_pro_9010_series_cyan_cartridge
    - sensor.hp_officejet_pro_9010_series_magenta_cartridge
    - sensor.hp_officejet_pro_9010_series_yellow_cartridge
  below: 05

action:
  service: persistent_notification.create
  data:
    message: "{{ trigger.to_state.attributes.friendly_name }} is at {{ trigger.to_state.state }}%"
    title: 'Ink level low'
    notification_id: xyz