alias: Livingroom-TV
trigger:
  - platform: webostv.turn_on
    entity_id: media_player.livingroom_tv
action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: 14:C9:13:CB:6B:47
      broadcast_address: 192.168.1.255
      broadcast_port: 9