binary_sensor:
  - name: Breezeway Door
    device_class: opening
    state: >
      {{ is_state("binary_sensor.breezeway_door_ias_zone", "on") }}
    icon: >
      {% if is_state("binary_sensor.breezeway_door_ias_zone", "on") %}
        mdi:door-open
      {% else %}
        mdi:door-closed
      {% endif %}