binary_sensor:
  - name: Deck Door
    device_class: opening
    state: >
      {{ is_state("binary_sensor.tuyatec_trhrga6p_rh3001_0e336ffe_ias_zone", "on") }}
    icon: >
      {% if is_state("binary_sensor.tuyatec_trhrga6p_rh3001_0e336ffe_ias_zone", "on") %}
        mdi:door-open
      {% else %}
        mdi:door-closed
      {% endif %}