binary_sensor:
  - name: Front Door
    device_class: opening
    state: >
      {{ is_state("binary_sensor.ewelink_ds01_29c1a423_ias_zone", "on") }}
    icon: >
      {% if is_state("binary_sensor.ewelink_ds01_29c1a423_ias_zone", "on") %}
        mdi:door-open
      {% else %}
        mdi:door-closed
      {% endif %}
