binary_sensor:
  - name: Front Door
    device_class: opening
    state: >
      {{ is_state("binary_sensor.front_door_iaszone_3", "on") }}
    icon: >
      {% if is_state("binary_sensor.front_door_iaszone_3", "on") %}
        mdi:door-open
      {% else %}
        mdi:door-closed
      {% endif %}
