
alias: Sync input_boolean.trash_town with town_trash_day
trigger:
  platform: state
  entity_id: sensor.town_trash_day
  to: "today"

action:
  service:
      input_boolean.turn_on

  entity_id: input_boolean.trash_town