
alias: Sync input_boolean.trash_day with hawkins_hurlbut
trigger:
  platform: state
  entity_id: sensor.hawkins_hurlbut

action:
  service_template: >
    {% if is_state('sensor.hawkins_hurlbut', 'today') %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.trash_day