
alias: Sync input_boolean.trash_day with hawkins_hurlbut
trigger:
  platform: state
  entity_id: sensor.hawkins_hurlbut
  to: "today"

action:
  service:
      input_boolean.turn_on

  entity_id: input_boolean.trash_day