
alias: Sync input_boolean.trash_town with town_trash_day
trigger:
  platform: state
  entity_id: sensor.town_trash_day

action:
  service_template: >
    {% if is_state('sensor.town_trash_day', 'today') %}
      input_boolean.turn_on
    {% else %}
      input_boolean.turn_off
    {% endif %}
  entity_id: input_boolean.trash_town