
alias: Today is trash day 
trigger:
  - platform: time
    at: '08:30:00'
  
condition:
- condition: state
  entity_id: sensor.hawkins_hurlbut
  state: "today"
  
action:
  service: notify.mobile_app_sm_n960u
  data:
    message: Did you take the trash out!
    title: Today is Trash Day
    data:
      actions:
      - action: out_yes
        title: 'Yes'
      - action: out_no
        title: 'No'