
# inside a automation actions or script sequence
alias: "Set up notification for trash day"
trigger:
  platform: time
  at: '08:30:00'
  variables:
  # Including an id in the action allows us to identify this script run
  # and not accidentally trigger for other notification actions
    action_on: "{{ 'ON_' ~ entity_id }}"
    action_off: "{{ 'OFF_' ~ entity_id }}"
    
condition:
  condition: state
  entity_id: sensor.hawkins_hurlbut
  state: "today"

action:
  - service: notify.mobile_app_ed_s_cell_phone
    data:
      message: "Did you take the trash out!"
      data:
        actions:
          - action: "{{ action_on }}"
            title: 'No'
          - action: "{{ action_off }}"
            title: 'Yes'

  - wait_for_trigger:
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          # waiting for the specific action avoids accidentally continuing
          # for another script/automation's notification action
          action: "{{ action_on }}"
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: "{{ action_off }}"

  - choose:
      - conditions: "{{ wait.trigger.event.data.action == action_on }}"
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: input_boolean.trash_day
      - conditions: "{{ wait.trigger.event.data.action == action_off }}"
        sequence:
          - service: input_boolean.turn_off
            target:
              entity_id: input_boolean.trash_day