substitutions:
  device: office_circuit
  Name: Office Shelly
  channel_1: Desktop
  channel_2: EWVA
  SSID: !secret wifi_iot_ssid
  SSID_PWD: !secret wifi_iot_password
  FB_PWD: !secret esphome_fallback_ap_password
  ESP_PWD: !secret esphome_password
  IP_Addr: 192.168.33.1
  max_power: "2000.0"
  max_temp: "176.0"

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${SSID:}
  password: ${SSID_PWD}
  ap:
    ssid: "${Name} Fallback Hotspot"
    password: ${FB_PWD}
#    manual_ip:
#      static_ip: ${IP_Addr}
#      gateway: 192.168.100.1
#      subnet: 255.255.255.0
#      dns1: 8.8.8.8
#      dns2: 8.8.4.4

captive_portal:

logger:
  level: DEBUG

api:
  password: ${ESP_PWD}

ota:
  password: ${ESP_PWD}

