substitutions:
  device: kitchen_lights
  Name: Kitchen Shelly
  channel_1: Sink Light
  channel_2: Cabinet Lights
  SSID: !secret wifi_iot_ssid
  SSID_PWD: !secret wifi_iot_password
  FB_PWD: !secret esphome_fallback_ap_password
  ESP_PWD: !secret esphome_password

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${SSID}
  password: ${SSID_PWD}
  ap:
    ssid: "${Name} Fallback Hotspot"
    password: "${FB_PWD}"
 
time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

logger:

api:
  password: ${ESP_PWD}

ota:
  password: ${ESP_PWD}

i2c:
  sda: GPIO12
  scl: GPIO14

sensor:
  - platform: ade7953
    voltage:
      name: ${Name} Voltage
    current_a:
      name: ${channel_2} Current
      id: current_channel_2
    current_b:
      name: ${channel_1} Current
      id: current_channel_1
    active_power_a:
      name: ${channel_2} Power
      id: power_channel_2
      filters:
        - multiply: 1
    active_power_b:
      name: ${channel_1} Power
      id: power_channel_1
      filters:
        - multiply: -1
    update_interval: 1s

  - platform: ntc
    sensor: temp_resistance_reading
    name: ${Name} Temperature
    filters:
      - lambda: return x * (9.0/5.0) + 32.0;
    unit_of_measurement: "°F"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_25_relay_1
  - platform: gpio
    pin: GPIO15
    id: shelly_25_relay_2

light:
  - platform: binary
    name: "${channel_1}"
    output: shelly_25_relay_1
    id: lightid1
  - platform: binary
    name: "${channel_2}"
    output: shelly_25_relay_2
    id: lightid2

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
    name: "${channel_1} input"
    internal: true
    on_state:
      then:
        - light.toggle: lightid1
  - platform: gpio
    pin:
      number: GPIO5
    name: "${channel_2} input"
    internal: true
    on_state:
      then:
        - light.toggle: lightid2
  - platform: gpio
    pin: GPIO16
    name: "ade7953 IRQ pin"
    internal: true
