substitutions:
  device: over-counter-lights
  Name: Counter Lights
  SSID: !secret wifi_iot_ssid
  SSID_PWD: !secret wifi_iot_password
  FB_PWD: !secret esphome_fallback_ap_password
  ESP_PWD: !secret esphome_password
  IP_Addr: 192.168.1.104

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${SSID}
  password: ${SSID_PWD}
  manual_ip:
    static_ip: ${IP_Addr}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1
  ap:
    ssid: "${Name} Fallback Hotspot"
    password: ${FB_PWD}

captive_portal:

web_server:
  port: 80

time:
  - platform: homeassistant
    id: homeassistant_time

logger:

api:
  password: ${ESP_PWD}

ota:
  password: ${ESP_PWD}

sensor:
  - platform: wifi_signal
    name: "${Name} WiFi Signal"
    update_interval: 60s

  - platform: uptime
    name: ${Name} Uptime

binary_sensor:
  - platform: status
    name: "${Name} Status"

  - platform: gpio
    pin:
      number: GPIO5
      #mode: INPUT_PULLUP
      #inverted: True
    name: "${Name}"
    on_state:
      - switch.toggle: shelly_relay
    #on_press:
    #  - switch.turn_on: lightid
    #on_release:
    #  - switch.turn_off: lightid
    internal: true
    id: switchid

text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${Name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${Name} IP
    ssid:
      name: ${Name} SSID
    bssid:
      name: ${Name} BSSID

output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

switch:
  - platform: gpio
    id: shelly_relay
    name: ${Name} Relay
    pin: GPIO4
    icon: "mdi:electric-switch"
