substitutions:
  device: eds-chair-light
  Name: Eds Chair Light
  SSID: !secret wifi_iot_ssid
  SSID_PWD: !secret wifi_iot_password
  FB_PWD: !secret esphome_fallback_ap_password
  ESP_PWD: !secret esphome_password
  IP_Addr: 192.168.1.154

esphome:
  name: ${device}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: ${SSID}
  password: ${SSID_PWD}
  ap:
    ssid: "${Name} Fallback Hotspot"
    password: "${FB_PWD}"

  manual_ip:
    static_ip: ${IP_Addr}
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

time:
  - platform: homeassistant
    id: homeassistant_time

captive_portal:

web_server:
  port: 80

logger:

api:
  password: ${ESP_PWD}

ota:
  password: ${ESP_PWD}

sensor:
  - platform: wifi_signal
    name: "${Name} WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: ${Name} Uptime
    
binary_sensor:
  - platform: status
    name: "${Name} Status"
    
text_sensor:
  # Expose ESPHome version as sensor.
  - platform: version
    name: ${Name} ESPHome Version
  # Expose WiFi information as sensors.
  - platform: wifi_info
    ip_address:
      name: ${Name} IP
    ssid:
      name: ${Name} SSID
    bssid:
      name: ${Name} BSSID

output:
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_daylight
    pin: GPIO5

light:
  - platform: cwww
    name: "${Name}"
    id: lightid
    cold_white: output_daylight
    warm_white: output_warm_white
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2700 K
    restore_mode: ALWAYS_OFF
