sensor:
  - name: Home Tank KWh
    unit_of_measurement: kWh
    state_class: total_increasing
    device_class: energy
    state: "{{ (states('sensor.home_tank_cubic_feet') | int(default=0) > 0 | float * 0.293) | round(3) }}"
