sensor:
  - name: Home Tank Cubic Feet
    unit_of_measurement: 'ft³'
    state_class: total_increasing
    device_class: gas
    state: "{{ (states('sensor.home_propane_tank_draw') | int(default=0) > 0 | float * 0.133681) | round(6)  }}"
