sensor:
  - name: "Home Propane Tank Fill"
    unit_of_measurement: 'gal'
    state: >
      {% set propane_usage = (states('sensor.home_tank_usage')) | default(0, true) | float %}
      {% if propane_usage > 0 %}
      {{ propane_usage | default(0, true) | float | round(2) }}
      {% else %}
      {{ 0 }}
      {% endif %}
    state_class: measurement
    unique_id: sense_home_propane_tank_fill
