sensor:
  - name: "Home Propane Tank Draw"
    unit_of_measurement: 'gal'
    state: >
      {% set propane_usage = (states('sensor.home_tank_usage')) | float(default=0) %}
      {% if propane_usage < 0 %}
      {{ propane_usage | float(default=0) * (-1) | round(2) }}
      {% else %}
      {{ 0 }}
      {% endif %}
    state_class: measurement
    unique_id: sense_home_propane_tank_draw
